### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by GrahamCampbell** [cachethq/cachethq.github.io#41]
Should we rename this repo to "cachethq.io", and rename the "master" branch to "gh-pages". That would make more sense as far as I can see. :)

// cc @cachethq/owners

**Comment by jbrooksuk** [comment]
Does that work with the CNAME stuff?

**Comment by GrahamCampbell** [comment]
Yeh, I use it on https://github.com/GrahamCampbell/grahamjcampbell.co.uk.

**Comment by jbrooksuk** [comment]
So if we use the `gh-pages` branch, can we use Jekyll still?

**Comment by GrahamCampbell** [comment]
Yeh. I'm using jekyll (I think). GitHub's gui does it all for me. :)

**Comment by jbrooksuk** [comment]
We can give it a go if it'll continue to work. Are we able to make use of other branches for things like docs?

**Comment by GrahamCampbell** [comment]
Not quite sure what you mean? If we want a docs.cachethq.io, then we just create a new repo with that name, push a gh-pages branch and include the CNAME file.

**Comment by jbrooksuk** [comment]
Ok, that's fine. If it's going to work then it makes sense to rename it.

**Comment by GrahamCampbell** [comment]
Will do then...

**Comment by GrahamCampbell** [comment]
Done. It could take upto 20 mins for github to fully process this change. NB, we may experience up to 10 mins of down time. Hopefully we won't though. :)

**Comment by jbrooksuk** [comment]
No problem :)

**Comment by GrahamCampbell** [comment]
Also, have you considered putting this domain behind cloudflare. It will allow us to use ssl on our website for free.

**Comment by GrahamCampbell** [comment]
I'm using this on my website, and it's powered by github pages.

**Comment by jbrooksuk** [comment]
@joecohens is in charge of the domain, so he'll have to take a look at that :)

**Comment by GrahamCampbell** [comment]
You can also auto-redirect people from www. and from http to https.

![image](https://cloud.githubusercontent.com/assets/2829600/5604295/a314fcc6-93ab-11e4-80e6-5a544d987e2c.png)

**Comment by GrahamCampbell** [comment]
NB, a `*` means 0 or more characters. :)

**Comment by joecohens** [comment]
I was setting up CloudFlare yesterday :) I was going to ask you what you think haha! I'm changing the DSN now.

**Comment by joecohens** [comment]
Done :) 

![screen shot 2015-01-03 at 8 16 22 pm](https://cloud.githubusercontent.com/assets/1803556/5604506/8827e2b4-9385-11e4-99cb-921e6e1b53ac.png)

**Comment by GrahamCampbell** [comment]
The first rule there should be removed. It conclits with the second.

**Comment by joecohens** [comment]
Removed.

**Comment by GrahamCampbell** [comment]
Also, you need to enable flexi SSL on CloudFlare

**Comment by joecohens** [comment]
Done. Should I set the www redirect?

**Comment by GrahamCampbell** [comment]
Yeh. You need to add the www DNS record too.

**Comment by joecohens** [comment]
Ok

**Comment by GrahamCampbell** [comment]
Still not working for me.

**Comment by joecohens** [comment]
For me it is but with a SSL not trusted.

**Comment by GrahamCampbell** [comment]
Very odd. You are using the the free version of CloudFlare?

**Comment by joecohens** [comment]
Yes. PM Gitter :)

**Comment by GrahamCampbell** [comment]
Ohh. They say give it 24houyrs. .

**Comment by GrahamCampbell** [comment]
https://www.cloudflare.com/ssl

**Comment by joecohens** [comment]
I've deleted the rules for now.

**Comment by GrahamCampbell** [comment]
Https is working for me now btw.

**Comment by joecohens** [comment]
Yep for me too. I'll add the rules again thanks ;)

**Comment by jbrooksuk** [comment]
@joecohens the status.cachethq.io domain no longer works.

**Comment by joecohens** [comment]
Fixing it right now thanks!

**Comment by GrahamCampbell** [comment]
Can you enable that "https only" rule please?

**Comment by joecohens** [comment]
Yeah I just did :)

**Comment by GrahamCampbell** [comment]
It will make sure search engines index the https version. Google ranks pages higher if they support http too. :)

**Comment by GrahamCampbell** [comment]
It doesn't seem to be working. Can you screenshot the rule please?

**Comment by GrahamCampbell** [comment]
Gitter...
